# Generated by Django 5.0.2 on 2024-02-17 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_commune', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('commune', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('code_qpv', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('nom_qpv', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('departement', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('region', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('statut_geo', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('code', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('federation', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('clubs', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('epa', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('total', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('date', models.DateField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='D_AGEGRP',
            fields=[
                ('agegrplabel', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='D_CLUB',
            fields=[
                ('code_code_qpv_code_commune', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('code', models.IntegerField()),
                ('code_qpv', models.CharField(max_length=20)),
                ('nom_qpv', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('federation', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('region', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('departement', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('nom_departement', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('code_commune', models.CharField(max_length=20)),
                ('commune', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('statut_geo', models.CharField(blank=True, default=None, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='D_DATE',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='D_ETABLISHEMENT',
            fields=[
                ('etablishementlabel', models.CharField(max_length=5, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='D_SEX',
            fields=[
                ('sexcode', models.CharField(max_length=5, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_commune', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('commune', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('code_qpv', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('nom_qpv', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('departement', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('region', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('statut_geo', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('code', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('federation', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('f_1_4_ans', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('f_5_9_ans', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('f_10_14_ans', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('f_15_19_ans', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('f_20_24_ans', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('f_25_29_ans', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('f_30_34_ans', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('f_35_39_ans', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('f_40_44_ans', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('f_45_49_ans', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('f_50_54_ans', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('f_55_59_ans', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('f_60_64_ans', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('f_65_69_ans', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('f_70_74_ans', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('f_75_79_ans', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('f_80_99_ans', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('f_nr', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('h_1_4_ans', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('h_5_9_ans', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('h_10_14_ans', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('h_15_19_ans', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('h_20_24_ans', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('h_25_29_ans', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('h_30_34_ans', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('h_35_39_ans', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('h_40_44_ans', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('h_45_49_ans', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('h_50_54_ans', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('h_55_59_ans', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('h_60_64_ans', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('h_65_69_ans', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('h_70_74_ans', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('h_75_79_ans', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('h_80_99_ans', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('h_nr', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('nr_nr', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('total', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='F_PLAYER',
            fields=[
                ('D_5_PK', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('D_CLUB_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.d_club')),
                ('D_SEX_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.d_sex')),
                ('D_AGEGRP_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.d_agegrp')),
                ('D_DATE_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.d_date')),
                ('D_ETABLISHEMENT_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.d_etablishement')),
                ('nombre', models.CharField(blank=True, default=None, max_length=10, null=True)),
            ],
            options={
                'unique_together': {('D_5_PK', 'D_CLUB_FK', 'D_SEX_FK', 'D_AGEGRP_FK', 'D_DATE_FK', 'D_ETABLISHEMENT_FK')},
            },
        ),
    ]
