# Generated by Django 5.0.2 on 2024-02-15 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
