# Generated by Django 5.0.2 on 2024-02-13 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_commune', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('commune', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('code_qpv', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('nom_qpv', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('departement', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('region', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('statut_geo', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('code', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('federation', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('clubs', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('epa', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('total', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='D_AGEGRP',
            fields=[
                ('AgeGrpLabel', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='D_COMMUNE',
            fields=[
                ('code_commune', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('commune', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='D_GEOPOSITION',
            fields=[
                ('region', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('departement', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('statut_geo', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='D_QPV',
            fields=[
                ('code_qpv', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nom_qpv', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='D_SEX',
            fields=[
                ('sexcode', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='last_name',
        ),
        migrations.AddField(
            model_name='player',
            name='code',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='code_commune',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='code_qpv',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='commune',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='departement',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='f_10_14_ans',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='f_15_19_ans',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='f_1_4_ans',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='f_20_24_ans',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='f_25_29_ans',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='f_30_34_ans',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='f_35_39_ans',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='f_40_44_ans',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='f_45_49_ans',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='f_50_54_ans',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='f_55_59_ans',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='f_5_9_ans',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='f_60_64_ans',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='f_65_69_ans',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='f_70_74_ans',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='f_75_79_ans',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='f_80_99_ans',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='f_nr',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='federation',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='h_10_14_ans',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='h_15_19_ans',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='h_1_4_ans',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='h_20_24_ans',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='h_25_29_ans',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='h_30_34_ans',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='h_35_39_ans',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='h_40_44_ans',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='h_45_49_ans',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='h_50_54_ans',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='h_55_59_ans',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='h_5_9_ans',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='h_60_64_ans',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='h_65_69_ans',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='h_70_74_ans',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='h_75_79_ans',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='h_80_99_ans',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='h_nr',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='nom_qpv',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='nr_nr',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='region',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='statut_geo',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='total',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='F_CLUB',
            fields=[
                ('F_code', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('federation', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('nb_epa', models.IntegerField(default=None)),
                ('nb_club', models.IntegerField(default=None)),
                ('total_value', models.IntegerField(default=None)),
                ('D_AGEGRP_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.d_agegrp')),
                ('D_CODE_COMMUNE_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.d_commune')),
                ('D_QPV_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.d_qpv')),
                ('D_SEX_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.d_sex')),
            ],
        ),
    ]
