# Generated by Django 5.0.2 on 2024-02-13 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_club_d_club_remove_player_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='d_club',
            name='code_code_qpv_code_commune',
        ),
        migrations.AddField(
            model_name='d_club',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
