# Generated by Django 5.0.2 on 2024-02-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='f_player',
            old_name='nombre',
            new_name='nombre_club',
        ),
        migrations.AddField(
            model_name='f_player',
            name='nombre_player',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
