# Generated by Django 5.0.2 on 2024-02-13 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_club_d_agegrp_d_commune_d_geoposition_d_qpv_d_sex_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='player',
            name='creation_date',
        ),
    ]
