# Generated by Django 5.0.2 on 2024-02-08 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
