# Generated by Django 5.0.2 on 2024-02-14 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_d_etablishement_etablishementlabel_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='d_etablishement',
            name='EtablishementLabel_Nombre',
        ),
    ]
