# Generated by Django 5.0.2 on 2024-02-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_club_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
