# Generated by Django 5.0.2 on 2024-02-13 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_d_club_code_code_qpv_code_commune_d_club_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='D_ETABLISHEMENT',
            fields=[
                ('EtablishementLabel', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Nombre', models.IntegerField()),
            ],
        ),
    ]
