# Generated by Django 5.0.2 on 2024-02-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_d_etablishement_etablishementlabel_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='d_etablishement',
            name='ETABLISHEMENT_ID',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
