# Generated by Django 5.0.2 on 2024-02-13 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_d_etablishement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='d_etablishement',
            name='Nombre',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
