# Generated by Django 5.0.2 on 2024-02-14 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_d_etablishement_etablishement_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='d_etablishement',
            old_name='ETABLISHEMENT_ID',
            new_name='Etablishement_id',
        ),
    ]
