# Generated by Django 5.0.2 on 2024-02-13 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_d_etablishement_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='d_etablishement',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='d_etablishement',
            name='EtablishementLabel',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
