# Generated by Django 5.0.2 on 2024-02-14 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_d_etablishement_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='d_etablishement',
            name='Nombre',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
