# Generated by Django 5.0.2 on 2024-02-14 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_agegrplabel_d_agegrp_agegrplabel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='d_date',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='d_etablishement',
            old_name='Etablishement_id',
            new_name='etablishement_id',
        ),
        migrations.RenameField(
            model_name='d_etablishement',
            old_name='EtablishementLabel',
            new_name='etablishementlabel',
        ),
        migrations.RenameField(
            model_name='d_etablishement',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='d_sex',
            old_name='SexCode',
            new_name='sexcode',
        ),
    ]
