# Generated by Django 5.0.2 on 2024-02-14 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_d_etablishement_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='D_SEX',
            fields=[
                ('SexCode', models.CharField(max_length=5, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='d_etablishement',
            name='Nombre',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
