# Generated by Django 5.0.2 on 2024-02-12 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='D_AGEGRP',
            fields=[
                ('AgeGrpLabel', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='D_COMMUNE',
            fields=[
                ('code_commune', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('commune', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='D_GEOPOSTION',
            fields=[
                ('region', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('departement', models.CharField(max_length=255)),
                ('statut_geo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='D_QPV',
            fields=[
                ('code', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nom_qpv', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='D_SEX',
            fields=[
                ('sexcode', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='F_CLUB',
            fields=[
                ('F_code', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('federation', models.CharField(max_length=255)),
                ('nb_epa', models.IntegerField()),
                ('nb_club', models.IntegerField()),
                ('total_value', models.IntegerField()),
                ('D_AGEGRP_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.d_agegrp')),
                ('D_CODE_COMMUNE_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.d_commune')),
                ('D_GEOPOSTION_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.d_geopostion')),
                ('D_QPV_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.d_qpv')),
                ('D_SEX_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.d_sex')),
            ],
        ),
    ]
