# Generated by Django 5.0.2 on 2024-02-14 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_d_sex_alter_d_etablishement_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='D_AGEGRP',
            fields=[
                ('AgeGrpLabel', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
        ),
    ]
