# Generated by Django 5.0.2 on 2024-02-14 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_d_agegrp'),
    ]

    operations = [
        migrations.CreateModel(
            name='D_DATE',
            fields=[
                ('Date', models.DateField(primary_key=True, serialize=False)),
            ],
        ),
    ]
