# Generated by Django 5.0.2 on 2024-02-14 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_d_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='F_PLAYER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_Club', models.IntegerField()),
                ('Total_Player', models.IntegerField()),
                ('D_AGEGRP_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.d_agegrp')),
                ('D_CLUB_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.d_club')),
                ('D_DATE_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.d_date')),
                ('D_ETABLISHEMENT_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.d_etablishement')),
                ('D_SEX_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.d_sex')),
            ],
        ),
    ]
